[theme]
primaryColor = "#3384beff"
backgroundColor = "#dcdcdcff"
secondaryBackgroundColor = "#c1cbe0ff"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
